- name: system setup | cron | install cron package
  tags: packages,cron
  package:
    name:
      - cron
    state: latest

- name: system setup | cron | schedule automatic ansible provisioning
  tags: cron
  cron:
    name: 'ansible provision'
    user: ansible
    minute: '*/10'
    job: '/usr/bin/ansible-pull -o -U https://github.com/esize/holy-grail > /dev/null'
