- name: package managers | asdf | install common dependencies
  become: yes
  apt:
    pkg:
      - curl
      - git
      - gnupg-agent
      - unzip
  tags: asdf

- name: package managers | asdf | check if asdf {{ asdf_version }} already installed
  stat:
    path: /opt/asdf-{{ asdf_version }}
  register: asdf_directory
  tags: asdf

- name: package managers | asdf | download asdf {{ asdf_version }}
  get_url:
    url: "https://github.com/asdf-vm/asdf/archive/v{{ asdf_version }}.tar.gz"
    dest: "/tmp/asdf-{{ asdf_version }}.tar.gz"
  tags: asdf
  when: not asdf_directory.stat.exists

- name: package managers | asdf | create asdf-{{ asdf_version }} directory
  file:
    path: "/opt/asdf-{{ asdf_version }}"
    state: directory
    mode: 0755
  tags: asdf

- name: package managers | asdf | install asdf {{ asdf_version }}
  unarchive:
    src: "/tmp/asdf-{{ asdf_version }}.tar.gz"
    extra_opts:
      - "--strip-components=1"
    dest: "/opt/asdf-{{ asdf_version }}"
    remote_src: yes
  tags: asdf
  when: not asdf_directory.stat.exists

- name: package managers | asdf | symlink default asdf
  file:
    src: "asdf-{{ asdf_version }}"
    dest: "/opt/asdf"
    state: link
  tags: asdf

- name: package managers | asdf | install asdf plugins
  command: "/opt/asdf/bin/asdf plugin add {{ item.name }}"
  args:
    creates: "{{ asdf_data_dir }}/plugins/{{ item.name }}"
  environment:
    ASDF_DATA_DIR: "{{ asdf_data_dir }}"
  with_items: "{{ asdf_plugins }}"
  become: "{{ asdf_become }}"
  tags: asdf

- name: package managers | asdf | install app versions for the asdf plugins
  command: "/opt/asdf/bin/asdf install {{ item.0.name }} {{ item.1 }}"
  args:
    creates: "{{ asdf_data_dir }}/installs/{{ item.0.name }}/{{ item.1 }}"
  environment:
    ASDF_DATA_DIR: "{{ asdf_data_dir }}"
    PATH: "{{ ansible_env.PATH }}:/opt/asdf/bin/"
  with_subelements:
    - "{{ asdf_plugins }}"
    - versions
    - flags:
      skip_missing: True
  become: "{{ asdf_become }}"
  tags: asdf

- name: package managers | asdf | read app default versions
  command: "/opt/asdf/bin/asdf current"
  environment:
    ASDF_DATA_DIR: "{{ asdf_data_dir }}"
    PATH: "{{ ansible_env.PATH }}:/opt/asdf/bin/"
  register: asdf_current_versions
  ignore_errors: True
  changed_when: False
  become: no
  tags: asdf

- name: package managers | asdf | define global asdf app default versions for the current user
  command: "/opt/asdf/bin/asdf global {{ item.name }} {{ item.global }}"
  environment:
    ASDF_DATA_DIR: "{{ asdf_data_dir }}"
  when: >
    item.global is defined and asdf_current_versions.stdout
    is not search(item.name|regex_escape + '\s+' +
                  item.global|regex_escape + '\s+')
  with_items: "{{ asdf_plugins }}"
  become: no
  tags: asdf
