- name: package managers | asdf
  include_vars:
    file: main.yml
- name: package managers | asdf | install common dependencies
  become: yes
  apt:
    pkg:
      - curl
      - git
      - gnupg-agent
      - unzip
  tags: asdf

- name: package managers | asdf | check if asdf {{ asdf_version }} already installed
  stat:
    path: /home/evan/.local/bin/asdf
  register: asdf_directory
  tags: asdf

- name: create tmp dir
  file:
    path: "/home/evan/tmp/{{ asdf_version }}/"
    state: directory
    owner: evan
    group: evan

- name: download archive
  get_url:
    url: "https://github.com/asdf-vm/asdf/archive/v{{ asdf_version }}.tar.gz"
    dest: "/home/evan/tmp"

- name: package managers | asdf | install asdf {{ asdf_version }}
  unarchive:
    src: "/home/evan/tmp/{{ asdf_version }}.tar.gz"
    extra_opts:
      - "--strip-components=1"
    dest: "/home/evan/.local/bin"
    include:
      - bin/asdf
    creates: /home/evan/.local/bin/asdf
    owner: "evan"
    group: "evan"
    mode: u+rwx
    remote_src: yes
  tags: asdf
  when: not asdf_directory.stat.exists
  become: yes
  become_user: "evan"

- name: package managers | asdf | move asdf binary
  copy:
    src: "home/evan/tmp/asdf/{{ asdf_version }}/bin/asdf"
    dest: /home/evan/.local/bin
    owner: evan
    group: evan


- name: package managers | asdf | Ensure .zshrc contains asdf configuration
  become: yes
  become_user: "evan"
  blockinfile:
    path: /home/evan/.zshrc
    block: |
      export ASDF_DATA_DIR=$HOME/.asdf
      export PATH="$ASDF_DATA_DIR/shims:$PATH"
    create: yes
  tags: asdf

- name: package managers | asdf | install asdf plugins
  shell: "/home/evan/.local/bin/asdf plugin add {{ item.name }}"
  args:
    executable: /bin/zsh  # Or /bin/zsh, depending on the user's shell
    creates: "/home/evan/.asdf/plugins/{{ item.name }}"
  environment:
    ASDF_DATA_DIR: "/home/evan/.asdf"
    PATH: "{{ ansible_env.PATH }}:$HOME/.local/bin:$HOME/.asdf/shims"
  become: yes
  become_user: "evan"
  tags: asdf
  with_items: "{{ asdf_plugins }}"

- name: package managers | asdf | install app versions for the asdf plugins
  shell: "/home/evan/.local/bin/asdf install {{ item.0.name }} {{ item.1 }}"
  args:
    executable: /bin/zsh  # Or /bin/zsh, depending on the user's shell
    creates: "/home/evan/.asdf/installs/{{ item.0.name }}/{{ item.1 }}"
  environment:
    ASDF_DATA_DIR: "/home/evan/.asdf"
    PATH: "{{ ansible_env.PATH }}:$HOME/.local/bin:$HOME/.asdf/shims"
  become: yes
  become_user: "evan"
  tags: asdf
  register: asdf_install_result
  ignore_errors: true
  with_subelements:
    - "{{ asdf_plugins }}"
    - versions
    - flags:
      skip_missing: True

- name: package managers | asdf | Fail if install app versions failed
  fail:
    msg: "asdf install failed for {{ item.0.name }} {{ item.1 }}. See error above."
  when: asdf_install_result.results|selectattr('item.0.name', 'equalto', item.0.name)|selectattr('item.1', 'equalto', item.1)|map(attribute='failed')|list|first
  with_subelements:
    - "{{ asdf_plugins }}"
    - versions
    - flags:
      skip_missing: True

- name: package managers | asdf | read app default versions
  command: "/home/evan/.local/bin/asdf current"
  environment:
    ASDF_DATA_DIR: "/home/evan/.asdf"
    PATH: "{{ ansible_env.PATH }}:$HOME/.local/bin:$HOME/.asdf/shims"
  register: asdf_current_versions
  ignore_errors: True
  changed_when: False
  become: yes
  become_user: "evan"
  tags: asdf

- name: package managers | asdf | define global asdf app default versions for the current user
  command: "/home/evan/.local/bin/asdf global {{ item.name }} {{ item.global }}"
  environment:
    ASDF_DATA_DIR: "/home/evan/.asdf"
    PATH: "{{ ansible_env.PATH }}:$HOME/.local/bin:$HOME/.asdf/shims"
  when: >
    item.global is defined and asdf_current_versions.stdout
    is not search(item.name|regex_escape + '\s+' +
                  item.global|regex_escape + '\s+')
  become: yes
  become_user: "evan"
  tags: asdf
  with_items: "{{ asdf_plugins }}"

- name: package managers | asdf | reshim
  command: "/home/evan/.local/bin/asdf reshim"
  environment:
    ASDF_DATA_DIR: "/home/evan/.asdf"
    PATH: "{{ ansible_env.PATH }}:$HOME/.local/bin:$HOME/.asdf/shims"
  become: yes
  become_user: "evan"
  tags: asdf

- name: package managers | asdf | set local version
  command: "/home/evan/.local/bin/asdf local {{ item.name }} {{ item.global }}"
  environment:
    ASDF_DATA_DIR: "/home/evan/.asdf"
    PATH: "{{ ansible_env.PATH }}:$HOME/.local/bin:$HOME/.asdf/shims"
  with_items: "{{ asdf_plugins }}"
  become: yes
  become_user: "evan"
  tags: asdf