- stat:
    path: /home/evan/.nvm
  register: nvm_path

- name: package managers | nvm | setup nvm
  become: yes
  become_flags: -i 
  become_user: evan 
  block:
    - name: package managers | nvm | install nvm
      shell: >
        curl -o- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash 
      args:
        chdir: "$HOME"
        creates: "$HOME/.nvm/nvm.sh"

- name: package managers | nvm | add {{extra_path}} to path
  lineinfile:
    dest: /etc/environment
    state: present
    backrefs: yes
    regexp: 'PATH=(["]*)((?!.*?"{{extra_path}}").*?)(["]*)$'
    line: 'PATH=\1\2:"{{extra_path}}"\3'
  vars:
    extra_path: "$HOME/.nvm/nvm.sh"
  when: nvm_path.stat.exists == false

- name: package managers | nvm | install node version using nvm
  become: yes
  become_flags: -i 
  become_user: evan 
  block:
  - name: package managers | nvm | install node versions using loop
    shell: >
      bash -c "source $HOME/.nvm/nvm.sh && nvm install v{{ item }}"
    args:
      executable: /bin/bash
    loop:
      - 22.14.0