- name: system setup | package cleanup | remove unneeded packages
  tags: cleanup,packages,system,settings
  package:
    state: absent
    name:
      - cowsay
      - exim4
      - exim4-base
      - exim4-config
      - nano
      - ubuntu-advantage-tools
      - ubuntu-pro-client-l10n
      - ubuntu-pro-client
      - distro-info
      - ubuntu-release-upgrader-core
      - python3-debian
      - python3-distupgrade
      - python3-update-manager

