version: '3'

services:
  web: &WEB
    build: .
    env_file:
      - .env
    ports:
      - 8000:80
    volumes:
      - files:/tmp/files

  jobs:
    build: .
    env_file:
      - .env
    volumes:
      - files:/tmp/files
    entrypoint: bundle exec script/delayed_job run

  db_initial:
    <<: *WEB
    entrypoint: bundle exec rake db:initial_setup

  reset_encryption_key:
    <<: *WEB
    entrypoint: bundle exec rake db:reset_encryption_key_hash

  bash:
    <<: *WEB
    entrypoint: /bin/bash

  postgres:
    image: postgres:9.6
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
  redis:
    image: redis

volumes:
  postgres:
  files:
