- hosts: all
  connection: local
  become: true
  pre_tasks:
    - name: update package cache
      apt: update_cache=yes
      changed_when: False

- hosts: all
  tags: base
  become: true
  roles:
    - base
