- hosts: all
  connection: ssh
  become: yes
  pre_tasks:
    - name: update package cache
      apt: 
        update_cache: yes
        cache_valid_time: 3600
      changed_when: False

- hosts: all
  connection: ssh
  tags: base
  roles:
    # - users
    # - dotfiles
    # - ssh
    # - docker
    - package-managers
    - packages
    - neovim
