- name: packages | system | zsh
  become: true
  ansible.builtin.apt:
    name: zsh
    state: latest

- name: packages | system | utilities
  become: true
  ansible.builtin.apt:
    name: 
      - aptitude
      - software-properties-common
      - curl
      - dnsutils
      - net-tools
      - nfs-common
      - rsync
      - sshfs
      - tmux
      - traceroute
      - wget
      - git
      - build-essential
      - unzip
    state: latest

- name: packages | system | uninstall
  become: true
  ansible.builtin.apt:
    state: absent
    name:
      - cowsay
      - exim4
      - exim4-base
      - exim4-config
      - nano

# - name: packages | system | oh my posh
#   become: yes
#   block:
#     - name: Ensure curl is installed
#       package:
#         name: curl
#         state: present

#     - name: Check if Oh My Posh is already installed
#       command: which oh-my-posh
#       register: oh_my_posh_installed
#       ignore_errors: yes


#     - name: Install Oh My Posh if not already installed
#       shell: curl -s https://ohmyposh.dev/install.sh | bash -s
#       when: oh_my_posh_installed.rc != 0