- name: git | gitconfig | add gitconfig
  copy:
    src: 'git/gitconfig'
    dest: /home/evan/.gitconfig
    owner: evan
    group: evan
    mode: 0600

- name: git | github cli | apt key
  ansible.builtin.get_url:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    dest: /usr/share/keyrings/githubcli-archive-keyring.gpg

- name: git | github cli | apt repo
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main'
    state: present

- name: git | github cli | install package
  ansible.builtin.apt:
    name: gh
    state: latest
    update_cache: true
