---

## check if installed and get latest version
- name: ssh | figurine | check if figurine is installed already
  stat:
    path: "{{ figurine_binary_path }}"
  register: binary_exists

- name: ssh | figurine | set fact if installed
  set_fact:
    figurine_is_installed: "{{ binary_exists.stat.exists }}"

- name: ssh | figurine | check figurine version
  shell: "{{ figurine_binary_path }} version | awk '{ print $3 }' | cut -c 2-"
  changed_when: false
  register: installed_version_registered
  when: figurine_is_installed == True

- name: ssh | figurine | get latest release
  uri:
    url: https://api.github.com/repos/arsham/figurine/releases/latest
    return_content: true
  register: release_version_registered
  when: figurine_download_latest_ver == True

- name: ssh | figurine | set figurine version (latest)
  set_fact:
    figurine_ver: "{{ release_version_registered.json.tag_name|regex_replace('v') }}"
  when: figurine_download_latest_ver == True

- name: ssh | figurine | set figurine version (pinned)
  set_fact:
    figurine_ver: "{{ figurine_pinned_ver }}"
  when: figurine_download_latest_ver == False

## install
- block:
    - name: ssh | figurine | Set Arch 
      set_fact:
        arch: "{% if '{{ ansible_architecture }}==x86_64' %}amd64{% else %} '{{ ansible_architecture }}' {% endif %}"

    ## v1.2.1 changed naming scheme
    - name: ssh | figurine | Set Download URL for v < 1.2.1
      set_fact:
        figurine_pkg_path: "v{{ figurine_ver }}/figurine_linux_v{{ figurine_ver }}.tar.gz"
      when: figurine_ver is version('1.2.1', '<')

    - name: ssh | figurine | Set Download URL for v > 1.2.0
      set_fact:
        figurine_pkg_path: "v{{ figurine_ver }}/figurine_linux_{{ arch }}_v{{ figurine_ver }}.tar.gz"
      when: figurine_ver is version('1.2.0', '>')
    
    - name: ssh | figurine | Extract figurine download into install path
      become: true
      unarchive:
        remote_src: true
        src: "{{ figurine_gh_url }}/{{ figurine_pkg_path }}"
        #src: "figurine_linux_v{{ figurine_ver }}.tar.gz"
        dest: "{{ figurine_system_bin_path }}"
        extra_opts: [--strip-components=1]

  when: figurine_is_installed == False or ( figurine_is_installed == True and figurine_download_latest_ver == True and installed_version_registered.stdout != figurine_ver ) or ( figurine_is_installed == True and figurine_download_latest_ver == False and installed_version_registered.stdout != figurine_pinned_ver )


## configurine
- name: ssh | figurine | configure login
  become: true
  template:
    src: figurine.sh.j2
    dest: /etc/update-motd.d/05-figurine
    mode: u+rwx,g+rx,o+rx

- name: ssh | figurine | remove other motd files
  become: true
  file:
    path: "/etc/update-motd.d/{{item}}"
    mode: -x
  loop:
    - 00-header
    - 10-help-text
    - 50-landscape-sysinfo
    - 50-motd-news
    - 90-updates-available
    - 91-contract-ua-esm-status
    - 91-release-upgrade
    - 92-unattended-upgrades
    - 95-hwe-eol
    - 97-overlayroot
    - 98-fsck-at-reboot