---
- name: "Set asdf environment variables for shell execution"
  ansible.builtin.set_fact:
    asdf_shell_env:
      ASDF_DATA_DIR: "{{ asdf_dir }}"
      ASDF_CONFIG_FILE: "{{ asdf_config_file }}"
      PATH: "{{ asdf_dir }}/shims:{{ asdf_bin_dir }}:/usr/local/bin:/usr/bin:/bin"

- name: "install asdf"
  import_tasks: "install.yml"
  tags: [asdf, asdf-install]
  
- name: "install plugins"
  import_tasks: "tools/main.yml"
  tags: [asdf, asdf-plugins]