# tasks/shell_config.yml

- name: "Get user's default shell"
  ansible.builtin.command: "getent passwd {{ asdf_user }}"
  register: user_shell_info
  changed_when: false

- name: "Set shell facts"
  ansible.builtin.set_fact:
    user_default_shell: "{{ user_shell_info.stdout.split(':')[-1] }}"
    is_zsh_default: "{{ '/zsh' in user_shell_info.stdout.split(':')[-1] }}"
    is_bash_default: "{{ '/bash' in user_shell_info.stdout.split(':')[-1] }}"
    user_home: "{{ user_shell_info.stdout.split(':')[5] }}"

- name: "Ensure asdf config directory exists"
  ansible.builtin.file:
    path: "{{ asdf_dir }}/shell"
    state: directory
    mode: '0755'
    owner: "{{ asdf_user }}"
    group: "{{ asdf_group }}"
  become: true
  become_user: "{{ asdf_user }}"

- name: "Configure shell rc files"
  ansible.builtin.template:
    dest: "{{ item.path }}"
    src: "{{ item.src }}"
    mode: '0644'
    owner: "{{ asdf_user }}"
    group: "{{ asdf_group }}"
  loop:
    - path: "{{ user_home }}/.zshrc"
      src: "asdf.zsh.j2"
      when: is_zsh_default
    - path: "{{ user_home }}/.bashrc"
      src: "asdf.bash.j2"
      when: is_bash_default
  when: "item.when | default(true)"
  become: true
  become_user: "{{ asdf_user }}"

- name: "Create tool-versions file"
  ansible.builtin.template:
    src: tool-versions.j2
    dest: "{{ asdf_dir }}/.tool-versions"
    mode: '0644'
    owner: "{{ asdf_user }}"
    group: "{{ asdf_group }}"
  become: true
  become_user: "{{ asdf_user }}"