- name: users | evan | create group
  tags: groups,evan,users
  group:
    name: evan
    state: present

- name: users | evan | create user
  tags: evan,sudo,users
  user:
    name: evan
    group: evan
    groups: adm,sudo,evan,wheel,docker
    state: present
    comment: 'Evan Sizemore'
    shell: /bin/zsh

- name: users | evan | evan | add sudoers file
  tags: evan,settings,ansible,sudo,system,users
  copy:
    src: users/sudoers_evan
    dest: /etc/sudoers.d/evan
    owner: root
    group: root
    mode: 0440

- name: users | evan | create .ssh directory
  tags: dotfiles,evan,ssh,users
  file:
    path: '{{ item.dir }}'
    state: directory
    owner: evan
    group: evan
    mode: 0700
  with_items:
    - { dir: '/home/evan/.ssh' }

- name: users | evan | add public key
  tags: dotfiles,evan,ssh,ssh-keys,users
  ansible.posix.authorized_key:
    user: evan
    key: https://github.com/esize.keys

- name: users | evan | copy dotfiles
  tags: dotfiles,users,evan,users,zsh
  copy:
    src: users/evan/{{ item.src }}
    dest: /home/evan/{{ item.dest }}
    owner: evan
    group: evan
    mode: 0600
  with_items:
    - { src: 'omp.toml', dest: '.config/omp/omp.toml' }


- name: users | evan | copy individual zsh config files
  tags: dotfiles,evan,users,zsh
  copy:
    src: users/evan/zsh/{{ item.src }}
    dest: /home/evan/.config/zsh/{{ item.src }}
    owner: evan
    group: evan
    mode: 0600
  with_items:
    - { src: 'aliases.zsh' }
    - { src: 'bindkey.zsh' }
    - { src: 'completion.zsh' }
    - { src: 'exports.zsh' }
    - { src: 'functions.zsh' }
    - { src: 'history.zsh' }
    - { src: 'path.zsh' }
    - { src: 'plugins.zsh' }
    - { src: 'setopt.zsh' }
    - { src: 'theming.zsh' }
    - { src: 'windows.zsh' }
