---
volumes:
  semaphore-mysql:
    driver: local
services:
  mysql:
    image: mysql:8.0
    hostname: mysql
    volumes:
      - semaphore-mysql:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    restart: unless-stopped
    networks:
      - internal
  semaphore:
    container_name: ansiblesemaphore
    image: semaphoreui/semaphore:v2.8.90
    user: '${UID}:${GID}'
    ports:
      - 3000:3000
    environment:
      - SEMAPHORE_DB_USER=<%= ENV['MYSQL_USER'] =%>
      - SEMAPHORE_DB_PASS=<%= ENV['MYSQL_PASSWORD'] =%>
      - SEMAPHORE_DB_HOST=mysql
      - SEMAPHORE_DB_PORT=3306
      - SEMAPHORE_DB_DIALECT=mysql
      - SEMAPHORE_DB=<%= ENV['MYSQL_DATABASE'] =%>
      - SEMAPHORE_PLAYBOOK_PATH=/tmp/semaphore/
      - ANSIBLE_HOST_KEY_CHECKING=false # (optional) change to true if you want to enable host key checking
    volumes:
      - ./inventory/:/inventory:ro
      - ./authorized-keys/:/authorized-keys:ro
      - ./config/:/etc/semaphore:rw
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      - proxy
      - internal
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.ansible.entrypoints=http'
      - 'traefik.http.routers.ansible.rule=Host(`ansible.local.wool.homes`)'
      - 'traefik.http.middlewares.ansible-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.ansible.middlewares=ansible-https-redirect'
      - 'traefik.http.routers.ansible-secure.entrypoints=https'
      - 'traefik.http.routers.ansible-secure.rule=Host(`ansible.local.wool.homes`)'
      - 'traefik.http.routers.ansible-secure.tls=true'
      - 'traefik.http.routers.ansible-secure.service=ansible'
      - 'traefik.http.services.ansible.loadbalancer.server.port=3000'
      - 'traefik.docker.network=proxy'

networks:
  proxy:
    external: true
  internal:
    external: false
