---
# defaults file for asdf
asdf_version: "v0.16.2"
asdf_user: "evan"
asdf_group: "evan"
asdf_dir: "/home/evan/.asdf"
asdf_bin_dir: /home/evan/.local/bin
asdf_bin: "{{ asdf_bin_dir }}/asdf"


asdf_config_file: "{{ asdf_dir }}/.asdfrc"
asdf_default_tool_versions_file: "{{ asdf_dir }}/.tool-versions"
asdf_legacy_version_file: no

asdf_plugins:
  - name: "nodejs"
    repository: ""
    versions:
      - 22.14.0
    global: 22.14.0
  - name: "neovim"
    repository: ""
    versions:
      - stable
    global: stable
  - name: "bat"
    repository: ""
    versions:
      - 0.25.0
    global: 0.25.0
  - name: "zoxide"
    repository: "https://github.com/nyrst/asdf-zoxide.git"
    versions:
      - latest
    global: latest
  - name: "eza"
    repository: "https://github.com/lwiechec/asdf-eza.git"
    versions:
      - latest
    global: latest
  # - name: "ripgrep"
  #   repository: "https://github.com/alk-adong/asdf-ripgrep.git"
  #   versions:
  #     - latest
  #   global: latest