- name: system setup | utilities | install utility packages
  tags: packages,system,settings
  package:
    state: latest
    name:
      - curl
      - dnsutils
      - net-tools
      - nfs-common
      - rsync
      - screen
      - sshfs
      - tmux
      - traceroute
      - neovim
      - wget
      - zsh
      - git

- name: install oh-my-posh
  get_url:
    url: https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-amd64
    dest: /usr/local/bin/oh-my-posh
    mode: u+rwx
    owner: evan
