- name: system setup | utilities | install utility packages
  tags: packages,system,settings
  package:
    state: latest
    name:
      - curl
      - dnsutils
      - net-tools
      - nfs-common
      - rsync
      - screen
      - sshfs
      - tmux
      - traceroute
      - neovim
      - wget
      - zsh
      - git
