services:
  it-tools:
    container_name: it-tools
    image: corentinth/it-tools:latest
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.it-tools.entrypoints=https
      - traefik.http.routers.it-tools.service=it-tools
      - traefik.http.routers.it-tools.rule=Host(`tools.local.wool.homes`)
      - traefik.http.routers.it-tools.tls=true
      - traefik.http.services.it-tools.loadbalancer.server.port=80

networks:
  proxy:
    external: true

