- block:    
    # Set up system users appropriately
    - import_tasks: users/root.yml
    - import_tasks: software/zsh.yml
    
    - import_tasks: users/evan.yml
    - import_tasks: users/ansible.yml

    # Install packages
    - import_tasks: software/repositories.yml
    - import_tasks: software/packages.yml
    - import_tasks: software/cleanup.yml
    - import_tasks: software/docker.yml
    - import_tasks: software/neovim.yml
    - import_tasks: software/cargo.yml

    - import_tasks: system/openssh.yml

  rescue:
    - set_fact: task_failed=true


