- block:
    # Set up system users appropriately
    - import_tasks: users/root.yml
    - import_tasks: users/evan.yml
    - import_tasks: users/ansible.yml

    # Set up the ansible environment
    - import_tasks: ansible_setup.yml

    # Install packages
    - import_tasks: software/repositories.yml
    - import_tasks: software/packages.yml
    - import_tasks: software/cleanup.yml

    # Ensure system is configured correctly
    - import_tasks: system/clock.yml
    - import_tasks: system/cron.yml
    - import_tasks: system/locale.yml
    - import_tasks: system/logging.yml
    - import_tasks: system/openssh.yml

  rescue:
    - set_fact: task_failed=true
