production: &production
  address: <%= ENV['SMTP_ADDRESS'] =%>
  port: <%= ENV['SMTP_PORT'] %>
  user_name: <%= ENV['SMTP_USER_NAME'] %>
  password: <%= ENV['SMTP_PASSWORD'] %>
  authentication: <%= ENV['SMTP_AUTHENTICATION'] %>
  domain: <%= ENV['SMTP_DOMAIN'] %>
  outgoing_address: <%= ENV['SMTP_OUTGOING_ADDRESS'] %>
  default_name: <%= ENV['SMTP_DEFAULT_NAME'] %>

development:
  <<: *production
