# oh_my_posh/tasks/main.yml
---
- name: Ensure required packages are installed
  package:
    name:
      - curl
      - unzip
    state: present

- name: Set installation directory
  set_fact:
    install_dir: "{{ install_dir | default(ansible_env.HOME + '/.local/bin') }}"

- name: Check if oh-my-posh is already installed
  command: which oh-my-posh
  register: posh_installed
  ignore_errors: true
  changed_when: false

- name: Determine install directory if oh-my-posh is installed
  set_fact:
    install_dir: "{{ posh_installed.stdout | dirname }}"
  when: posh_installed.rc == 0

- name: Create installation directory if it does not exist
  file:
    path: "{{ install_dir }}"
    state: directory
    mode: '0755'

- name: Download oh-my-posh executable
  get_url:
    url: "https://cdn.ohmyposh.dev/releases/{{ version }}/posh-linux-amd64"
    dest: "{{ install_dir }}/oh-my-posh"
    mode: '0755'
  when: posh_installed.rc != 0

- name: Add install_dir to PATH
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH=$PATH:{{ install_dir }}'
    state: present
