---
- name: Converge
  hosts: all
  become: yes

  tasks:
    - name: Include this role
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        asdf_plugins:
          - name: adr-tools
            versions:
              - 3.0.0
            global: 3.0.0
          - name: terraform
            versions:
              - 0.12.26
              - 0.14.2
            global: 0.14.2
          - name: yarn
            versions:
              - 1.22.10
